### ISSUE TITLE
Cluster auto-assign throws error for non-default blueprints

### ISSUE THREAD

**Issue by zbears** [sequenceiq/ambari-shell#41]
For any blueprint that is not a default blueprint (i.e. one that has been added from a file), I get the following error when using cluster autoAssign:
```
CLUSTER_BUILD:hdpsparkhive>cluster autoAssign
Command failed java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/sequenceiq/ambari/client/InvalidHostGroupHostAssociation.<init>(Ljava/lang/String;I)V @91: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184e 04bd 001a 5903 2b53 5908 1204
    0000010: b800 205a 047e 9900 0803 32c0 0022 5f2a
    0000020: 5f10 087a ab00 0000 0000 00b7 0000 0005
    0000030: 0000 0000 0000 0034 0000 0001 0000 003d
    0000040: 0000 0002 0000 0052 0000 0003 0000 0073
    0000050: 0000 0004 0000 00a2 5f5a 57b7 0025 a700
    0000060: 875f 5a59 0332 1227 b800 2bc0 0027 5f57
    0000070: b700 2ea7 0072 5f5a 5903 3212 27b8 002b
    0000080: c000 275f 5904 3212 30b8 002b c000 305f
    0000090: 57b7 0033 a700 515f 5a59 0332 1227 b800
    00000a0: 2bc0 0027 5f59 0432 1230 b800 2bc0 0030
    00000b0: 5f59 0532 b800 395f 5906 32b8 0039 5f57
    00000c0: b700 3ca7 0022 5f5a 5903 3212 30b8 002b
    00000d0: c000 305f 57b7 003f a700 0dbb 0041 5912
    00000e0: 43b7 0044 bf57 2ab6 0048 3a04 1904 2a5f
    00000f0: b500 4a19 0457 1c36 0515 05b8 0050 b800
    0000100: 542a 5fb5 0056 1505 57b1               
  Stackmap Table:
    full_frame(@30,{UninitializedThis,Object[#39],Integer,Object[#92]},{Integer,Object[#34]})
    full_frame(@88,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@97,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@118,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@151,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@198,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@219,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@229,{Object[#2],Object[#39],Integer,Object[#92]},{Object[#34]})

Exception in thread "Spring Shell" java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/sequenceiq/ambari/client/InvalidHostGroupHostAssociation.<init>(Ljava/lang/String;I)V @91: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: b800 184e 04bd 001a 5903 2b53 5908 1204
    0000010: b800 205a 047e 9900 0803 32c0 0022 5f2a
    0000020: 5f10 087a ab00 0000 0000 00b7 0000 0005
    0000030: 0000 0000 0000 0034 0000 0001 0000 003d
    0000040: 0000 0002 0000 0052 0000 0003 0000 0073
    0000050: 0000 0004 0000 00a2 5f5a 57b7 0025 a700
    0000060: 875f 5a59 0332 1227 b800 2bc0 0027 5f57
    0000070: b700 2ea7 0072 5f5a 5903 3212 27b8 002b
    0000080: c000 275f 5904 3212 30b8 002b c000 305f
    0000090: 57b7 0033 a700 515f 5a59 0332 1227 b800
    00000a0: 2bc0 0027 5f59 0432 1230 b800 2bc0 0030
    00000b0: 5f59 0532 b800 395f 5906 32b8 0039 5f57
    00000c0: b700 3ca7 0022 5f5a 5903 3212 30b8 002b
    00000d0: c000 305f 57b7 003f a700 0dbb 0041 5912
    00000e0: 43b7 0044 bf57 2ab6 0048 3a04 1904 2a5f
    00000f0: b500 4a19 0457 1c36 0515 05b8 0050 b800
    0000100: 542a 5fb5 0056 1505 57b1               
  Stackmap Table:
    full_frame(@30,{UninitializedThis,Object[#39],Integer,Object[#92]},{Integer,Object[#34]})
    full_frame(@88,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@97,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@118,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@151,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@198,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@219,{UninitializedThis,Object[#39],Integer,Object[#92]},{Object[#34],UninitializedThis})
    full_frame(@229,{Object[#2],Object[#39],Integer,Object[#92]},{Object[#34]})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2532)
	at java.lang.Class.getDeclaredConstructors(Class.java:1901)
	at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:69)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:64)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:258)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:189)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:193)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:148)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:131)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:175)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:192)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:806)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.sequenceiq.ambari.client.AmbariClient.recommendAssignments(AmbariClient.groovy:519)
	at com.sequenceiq.ambari.shell.commands.ClusterCommands.autoAssign(ClusterCommands.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:196)
	at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
	at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
	at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:127)
	at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zbears** [comment]
It appears that this is a java version error. I'm running the recommended java version for Ambari. What version was the shell designed for?

**Comment by keyki** [comment]
Did you try to use the autoAssign command? It has a requirement that each host group's name is similar to slave_X and one master host group. If it's not feasible for you use the manual host - host group association. 

This issue happens on a specific java version, but I cant remember on which version, _67 maybe.

**Comment by zbears** [comment]
I was not aware of the slave_X and master requirement. I've tried 7_67, 7_79, 5, and 8 so I'm starting to doubt that it's a java version. I'll try to change the naming of the host groups to see if that fixes it.

**Comment by zbears** [comment]
Yep. The slave and master names fixed it. Thanks for your help!
